algo = input("Digite algo: ")

print("O tipo primitivo desse valor é {}".format(type(algo)))
print("Só tem espaço? {}" .format(algo.isspace()))
print("É um número? {}" .format(algo.isnumeric()))
print("É alfabético? {}" .format(algo.isalpha()))
print("É alfanumérico? {}" .format(algo.isalnum()))
print("É maiúsculo {}" .format(algo.isupper()))
print("É minúsculo? {}" .format(algo.islower()))
print("Está capitalizada? {}" .format(algo.istitle()))
